### ISSUE TITLE
Bugs encontrados na reunião de entrega

### ISSUE THREAD

**Issue by jorgesallum** [jorgesallum/SciELO-EdO#19]
- [ ] Opção notas de fim não funciona e template atual (Registrado no #23 )
- [ ] Opção retirar cabeço não está compatível com templates SciELO (provisório) sem cabeço (Registrado no #27)
- [ ] Opção colocar índice não está compatível com templates SciELO provisórios  (Registrado no #25)

**Comment by amandasramalho** [comment]
Na verdade o ideal seria se cada um destes tópicos fossem tickets independentes e cada um validado separadamente, desta forma que está neste ticket as discussões podem se misturar.

**Comment by amandasramalho** [comment]
#23
